"""changed route

Revision ID: 2dff4733d1e1
Revises: 6c9fc589b5fc
Create Date: 2022-11-04 14:18:46.811299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dff4733d1e1'
down_revision = '6c9fc589b5fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
