"""init routes

Revision ID: abf06dc0d08c
Revises: 78ff5bd54955
Create Date: 2022-11-04 11:52:03.397069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf06dc0d08c'
down_revision = '78ff5bd54955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('point_a_id', sa.Integer(), nullable=False),
    sa.Column('point_b_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['point_a_id'], ['point.id'], ),
    sa.ForeignKeyConstraint(['point_b_id'], ['point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route')
    # ### end Alembic commands ###
